[tool.poetry]
name = "sportorgplus"
version = "1.1.0"
description = "SportOrgPlus, fork of SportOrg"
authors = ["Danil Akhtarov <daxartio@gmail.com>, Semyon Yakimov <sdyakimov@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.8"
boltons = "^20"
cx_Freeze = "^6"
docxtpl = "^0"
jinja2 = "^2"
playsound = "^1"
polib = "^1"
pydantic = "^1"
PySide2 = "^5"
python-dateutil = "^2"
python-dotenv = '^0.14'
#pywin32 = "^228"
#pywinusb = "^0"
requests = "^2"
shiboken2 = "^5.15"
sportident = "^1"

[tool.poetry.dev-dependencies]
autoflake = "*"
black = {version = "*", allow-prereleases = true}
flake8 = "*"
flake8-annotations-complexity = "*"
flake8-bandit = "*"
flake8-breakpoint = "*"
flake8-bugbear = "*"
flake8-builtins = "*"
flake8-comprehensions = "*"
flake8-eradicate = "*"
flake8-if-expr = "*"
flake8-isort = "*"
flake8-logging-format = "*"
flake8-print = "*"
flake8-pytest = "*"
flake8-pytest-style = "*"
flake8-requirements = "*"
flake8-return = "*"
mypy = "*"
pep8-naming = "*"
pylint = "*"
pytest = "*"
pytest-cov = "*"
pytest-deadfixtures = "*"
pytest-mock = "*"
toml = "*"
unify = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
