name: Build

on:
  push:
    #branches: [ $default-branch ]
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x86, x64]
    name: Build on Windows ${{ matrix.architecture }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        id: set_up_python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: ${{ matrix.architecture }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_win.txt
      - name: Build
        run: |
          python setup_.py build
      - name: Generate installer
        run: |
          python setup_.py bdist_msi
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          path: dist/*.msi
      - name: Generate Changelog
        run: |
          # Get text after ## ... <version> from changelog.ru.md and changelog.en.md
          sed -n "/^##.*${{ github.ref_name }}.*$/,/^##/{/^##/d ; p}" changelog.ru.md | sed -z "s/^\n*//g" - > ${{ github.workspace }}-CHANGELOG.txt
          printf "\n---\n" >> ${{ github.workspace }}-CHANGELOG.txt
          sed -n "/^##.*${{ github.ref_name }}.*$/,/^##/{/^##/d ; p}" changelog.en.md | sed -z "s/^\n*//g" - >> ${{ github.workspace }}-CHANGELOG.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: |
            dist/*.msi


# vim: ts=2 sw=2 et
