name: CI Tests/Lints

on:
  push:
    paths:
      - "sportorg/**"
      - "tests/**"
      - "docs/**"
      - ".github/workflows/*"
  workflow_dispatch:

jobs:
  #lint:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v4
  #    - uses: actions/setup-python@v5
  #      with:
  #        python-version: '3.8'

  #    - name: Install python dependencies
  #      run: |
  #        python -m pip install --upgrade pip
  #        pip install --upgrade wheel # fix playsound installing
  #        pip install -r requirements.txt

  #    - name: Run linters
  #      run: poetry run poe lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Init .env
        run: cp .env.example .env

      - name: Install socat
        run: |
          sudo apt update
          sudo apt install socat

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade wheel # fix playsound installing
          pip install -r requirements.txt


      - name: Run test
        run: pytest -vv

# vim: ts=2 sw=2 et
